apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: gitea
    gitName: gitea
    gitServer: http://gitea.gitea
    provider: kind
    registry: localhost:5000
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "svc.cluster.local"
    externalDNS: false
    ignoreLoadBalancer: true
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  webhook: lighthouse
